default: &default
  adapter: postgresql
  username: postgres
  password:
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: tvshow_development
test:
  <<: *default
  database: tvshow_test
